network:
  version: 1
  config:
    - type: physical
      name: ens3
      subnets:
        - type: static
          ipv4: true
          address: ${host_ip_address}
          netmask: 255.255.255.0
          gateway: 192.168.2.254
          control: auto
        - type: nameserver
          address:
            - 192.168.2.130
            - 192.168.2.128
            - 192.168.2.129
          search:
            - griend.dev

