#cloud-config
hostname: ${hostname}
manage_etc_hosts: false
ssh_pwauth: false
disable_root: false
users:
  - name: ${username}
    passwd: ${password}
    lock-passwd: false
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ${ssh_public_key}

growpart:
  mode: auto
  devices: ["/"]
  ignore_growroot_disabled: false

package_update: true
package_upgrade: true
packages:
  - qemu-guest-agent

runcmd:  
  - [ systemctl, start, qemu-guest-agent ]
