network:
    version: 2
    renderer: networkd
    ethernets:
        ens3:
            dhcp4: no
            addresses:
            - {{ host_ip_address }}
            gateway4: 192.168.2.254
            nameservers:
              addresses:
                - 192.168.2.128
                - 192.168.2.129
                - 192.168.2.130
